"""
Tests for the User and KnowledgeBase models.

These deliberately test constraint *behavior*, not just "can I insert a
row" — an autogenerated migration can create a table that accepts inserts
just fine while still having the wrong nullable/unique/cascade settings.
The whole point of the per-user-isolation requirement is that these
constraints hold under real SQL, so that's what gets tested.
"""

import pytest
from sqlalchemy import select
from sqlalchemy.exc import IntegrityError
from sqlalchemy.ext.asyncio import AsyncSession

from app.models import KnowledgeBase, User


@pytest.mark.asyncio
async def test_create_user(db_session: AsyncSession):
    user = User(email="student@example.com", hashed_password="not-a-real-hash")
    db_session.add(user)
    await db_session.commit()
    await db_session.refresh(user)

    assert user.id is not None
    assert user.is_active is True
    assert user.created_at is not None


@pytest.mark.asyncio
async def test_email_must_be_unique(db_session: AsyncSession):
    db_session.add(User(email="dup@example.com", hashed_password="x"))
    await db_session.commit()

    db_session.add(User(email="dup@example.com", hashed_password="y"))
    with pytest.raises(IntegrityError):
        await db_session.commit()


@pytest.mark.asyncio
async def test_knowledge_base_belongs_to_owner(db_session: AsyncSession):
    user = User(email="owner@example.com", hashed_password="x")
    db_session.add(user)
    await db_session.commit()
    await db_session.refresh(user)

    kb = KnowledgeBase(name="ML coursework", owner_id=user.id)
    db_session.add(kb)
    await db_session.commit()
    await db_session.refresh(kb)

    assert kb.owner_id == user.id


@pytest.mark.asyncio
async def test_deleting_user_cascades_to_knowledge_bases(db_session: AsyncSession):
    user = User(email="cascade@example.com", hashed_password="x")
    db_session.add(user)
    await db_session.commit()
    await db_session.refresh(user)

    db_session.add(KnowledgeBase(name="Will be deleted", owner_id=user.id))
    await db_session.commit()

    await db_session.delete(user)
    await db_session.commit()

    remaining = await db_session.execute(select(KnowledgeBase))
    assert remaining.scalars().all() == []
