"""add source_url to documents

Revision ID: 348bbb1d778c
Revises: a7c4e9f1b3d6
Create Date: 2026-09-16 08:41:24.651465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '348bbb1d778c'
down_revision: Union[str, None] = 'a7c4e9f1b3d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('source_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'source_url')
    # ### end Alembic commands ###
