"""make file_size_bytes and storage_path nullable for url-sourced documents

Revision ID: 6fe99807a2ef
Revises: 7b103c612b2a
Create Date: 2026-09-16 08:58:19.471367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fe99807a2ef'
down_revision: Union[str, None] = '7b103c612b2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
