"""make file_size_bytes and storage_path nullable for url-sourced documents

Revision ID: 7b103c612b2a
Revises: 348bbb1d778c
Create Date: 2026-09-16 08:55:59.867874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b103c612b2a'
down_revision: Union[str, None] = '348bbb1d778c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'file_size_bytes',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('documents', 'storage_path',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'storage_path',
               existing_type=sa.VARCHAR(length=1024),
               nullable=False)
    op.alter_column('documents', 'file_size_bytes',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
