"""add full-text search column and GIN index to document_chunks

Revision ID: 8cfb5c4463f9
Revises: 20364b3c6ed8
Create Date: 2026-08-19 04:39:02.421205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8cfb5c4463f9'
down_revision: Union[str, None] = '20364b3c6ed8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunks', sa.Column('text_search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', text)", persisted=True), nullable=True))
    op.create_index('ix_document_chunks_text_search_vector', 'document_chunks', ['text_search_vector'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_document_chunks_text_search_vector', table_name='document_chunks', postgresql_using='gin')
    op.drop_column('document_chunks', 'text_search_vector')
    # ### end Alembic commands ###
