"""add page_number to document_chunks

Revision ID: f3a1c9d2e5b7
Revises: 8cfb5c4463f9
Create Date: 2026-09-05 09:30:00.000000

NOTE: hand-written, not autogenerated. This development session had no
network access to install Postgres/run `alembic revision --autogenerate`
against a live database (see Phase 9 notes in README.md) — the previous
phases' migrations were all generated against a real running database and
inspected before applying; this one is written by hand following the exact
same column-add pattern as 8cfb5c4463f9 and has NOT been applied or tested
against a real Postgres instance. Run and verify this migration (`alembic
upgrade head` against a real dev/test database) before trusting it in
place of a freshly autogenerated one.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'f3a1c9d2e5b7'
down_revision: Union[str, None] = '8cfb5c4463f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('document_chunks', sa.Column('page_number', sa.Integer(), nullable=True))


def downgrade() -> None:
    op.drop_column('document_chunks', 'page_number')
